# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 22) do

  create_table "activities", :force => true do |t|
    t.column "activity_type_id", :integer
    t.column "time",             :datetime
    t.column "notes",            :text
    t.column "user_id",          :integer
  end

  add_index "activities", ["activity_type_id"], :name => "index_activities_on_activity_type_id"
  add_index "activities", ["user_id"], :name => "index_activities_on_user_id"

  create_table "activities_contacts", :id => false, :force => true do |t|
    t.column "activity_id", :integer
    t.column "contact_id",  :integer
  end

  add_index "activities_contacts", ["activity_id"], :name => "index_activities_contacts_on_activity_id"
  add_index "activities_contacts", ["contact_id"], :name => "index_activities_contacts_on_contact_id"

  create_table "activity_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "addresses", :force => true do |t|
    t.column "address1", :string
    t.column "address2", :string
    t.column "city",     :string
    t.column "state",    :string
    t.column "zip",      :string
    t.column "country",  :string
  end

  create_table "contacts", :force => true do |t|
    t.column "first_name",     :string
    t.column "last_name",      :string
    t.column "email",          :string
    t.column "phone_number",   :string
    t.column "title",          :string
    t.column "work_phone",     :string
    t.column "mobile_phone",   :string
    t.column "home_phone",     :string
    t.column "other_phone",    :string
    t.column "fax",            :string
    t.column "do_not_email",   :boolean
    t.column "do_not_phone",   :boolean
    t.column "notes",          :text
    t.column "address_id",     :integer
    t.column "address2_id",    :integer
    t.column "lead_source_id", :integer
  end

  add_index "contacts", ["address2_id"], :name => "index_contacts_on_address2_id"
  add_index "contacts", ["address_id"], :name => "index_contacts_on_address_id"
  add_index "contacts", ["lead_source_id"], :name => "index_contacts_on_lead_source_id"

  create_table "contacts_groups", :id => false, :force => true do |t|
    t.column "contact_id", :integer
    t.column "group_id",   :integer
  end

  add_index "contacts_groups", ["contact_id"], :name => "index_contacts_groups_on_contact_id"
  add_index "contacts_groups", ["group_id"], :name => "index_contacts_groups_on_group_id"

  create_table "dynamic_attribute_values", :force => true do |t|
    t.column "dynamic_attribute_id", :integer
    t.column "contact_id",           :integer
    t.column "string_value",         :string
    t.column "text_value",           :text
    t.column "integer_value",        :integer
    t.column "decimal_value",        :decimal
    t.column "datetime_value",       :datetime
    t.column "boolean_value",        :boolean
  end

  add_index "dynamic_attribute_values", ["contact_id"], :name => "index_dynamic_attribute_values_on_contact_id"
  add_index "dynamic_attribute_values", ["dynamic_attribute_id"], :name => "index_dynamic_attribute_values_on_dynamic_attribute_id"

  create_table "dynamic_attributes", :force => true do |t|
    t.column "name",      :string
    t.column "type_name", :string
  end

  create_table "email_messages", :force => true do |t|
    t.column "activity_id", :integer
    t.column "subject",     :string
    t.column "body",        :text
  end

  create_table "group_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "groups", :force => true do |t|
    t.column "name",                :string
    t.column "account_number",      :integer
    t.column "phone",               :string
    t.column "fax",                 :string
    t.column "website",             :string
    t.column "notes",               :text
    t.column "billing_address_id",  :integer
    t.column "shipping_address_id", :integer
    t.column "group_type_id",       :integer
    t.column "parent_id",           :integer
    t.column "lft",                 :integer
    t.column "rgt",                 :integer
    t.column "root_id",             :integer
    t.column "depth",               :integer
  end

  add_index "groups", ["billing_address_id"], :name => "index_groups_on_billing_address_id"
  add_index "groups", ["group_type_id"], :name => "index_groups_on_group_type_id"
  add_index "groups", ["lft"], :name => "index_groups_on_lft"
  add_index "groups", ["parent_id"], :name => "index_groups_on_parent_id"
  add_index "groups", ["rgt"], :name => "index_groups_on_rgt"
  add_index "groups", ["root_id"], :name => "index_groups_on_root_id"
  add_index "groups", ["shipping_address_id"], :name => "index_groups_on_shipping_address_id"

  create_table "lead_sources", :force => true do |t|
    t.column "name", :string
  end

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

  add_index "users", ["login", "crypted_password"], :name => "index_users_on_login_and_crypted_password"

end
